(() => {
  const cfg = window.LAIT_DIVIN_CONFIG || {};
  let sb = null;
  try { if (cfg.SUPABASE_URL && cfg.SUPABASE_ANON_KEY && window.supabase) sb = window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY); } catch (e) { console.warn(e); }
  const $ = (s, r=document) => r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const money = n => new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n)||0);
  const today = () => new Date().toISOString().slice(0,10); const nowTime=()=>new Date().toTimeString().slice(0,5);
  const store = {
    get(k,d){ try{return JSON.parse(localStorage.getItem('ld_'+k)) ?? d}catch{return d}},
    set(k,v){localStorage.setItem('ld_'+k,JSON.stringify(v))}
  };
  const defaults = {
    sales:[{id:1,date:today()+' 18:42',product:'ミルキージュエルパフェ',staff:'神崎 結城',qty:2,total:80000,cost:36000},{id:2,date:today()+' 17:15',product:'トロピカル・フォックス',staff:'鷹 勇',qty:3,total:150000,cost:60000},{id:3,date:today()+' 15:10',product:'ピーチ&ミルク フロリーノ',staff:'栗村 おもち',qty:1,total:50000,cost:21000}],
    inventory:[{id:1,name:'牛乳',stock:42,min:20,unit:'本'},{id:2,name:'いちご',stock:12,min:15,unit:'箱'},{id:3,name:'ブルーハワイシロップ',stock:7,min:10,unit:'本'},{id:4,name:'桃',stock:26,min:12,unit:'箱'},{id:5,name:'マンゴー',stock:18,min:12,unit:'箱'},{id:6,name:'カップ',stock:130,min:50,unit:'個'}],
    staff:[{id:1,name:'神崎 結城',role:'Owner',rate:200000,status:'在籍'},{id:2,name:'鷹 勇',role:'Store Manager',rate:160000,status:'在籍'},{id:3,name:'栗村 おもち',role:'Supervisor',rate:120000,status:'在籍'},{id:4,name:'椿姫 優太',role:'Cast',rate:80000,status:'在籍'}],
    news:[{id:1,date:today(),title:'夏限定メニュー販売開始',body:'トロピカル・フォックスとミルキージュエルパフェの販売を開始しました。'},{id:2,date:today(),title:'Farm燃料費について',body:'Farmに参加した方へ、毎週50万円の燃料費を支給します。'}],
    payroll:[{id:1,name:'神崎 結城',period:'今週',base:1600000,bonus:500000,farm:500000},{id:2,name:'鷹 勇',period:'今週',base:1280000,bonus:350000,farm:500000}],
    attendance:[]
  };
  Object.keys(defaults).forEach(k=>{if(localStorage.getItem('ld_'+k)===null)store.set(k,defaults[k])});
  let role='employee', currentUser={name:'ゲスト',email:'demo@lait-divin.local'}, attendanceActive=store.get('attendanceActive',false);
  const toast=t=>{const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)};
  $$('.role-tab').forEach(b=>b.onclick=()=>{$$('.role-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');role=b.dataset.role;$('#loginHint').textContent=role==='admin'?'管理者権限を持つアカウントでログインしてください。':'Supabase Authの登録済みアカウントでログインします。'});
  $('#loginForm').addEventListener('submit',async e=>{e.preventDefault(); const email=$('#email').value.trim(),password=$('#password').value; if(!sb)return toast('Supabase設定を確認してください'); const {data,error}=await sb.auth.signInWithPassword({email,password}); if(error)return toast(error.message); currentUser={name:data.user.user_metadata?.name||email.split('@')[0],email}; if(email===cfg.ADMIN_EMAIL)role='admin'; openApp();});
  $('#demoButton').onclick=()=>{role=$('.role-tab.active').dataset.role;currentUser={name:role==='admin'?'管理者デモ':'従業員デモ',email:'demo@lait-divin.local'};openApp()};
  function openApp(){ $('#authView').classList.add('hidden');$('#appView').classList.remove('hidden'); document.body.classList.toggle('admin-mode',role==='admin'); $$('.admin-only').forEach(el=>el.classList.toggle('hidden',role!=='admin')); $('#profileName').textContent=currentUser.name;$('#welcomeName').textContent=currentUser.name;$('#profileRole').textContent=role==='admin'?'管理者':'従業員';$('#profileAvatar').textContent=currentUser.name.slice(0,1);renderAll(); }
  $('#logoutButton').onclick=async()=>{if(sb)await sb.auth.signOut();location.reload()};
  $('#themeButton').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('ld_theme',document.body.classList.contains('dark')?'dark':'light')}; if(localStorage.getItem('ld_theme')==='dark')document.body.classList.add('dark');
  $('#menuButton').onclick=()=>$('.sidebar').classList.toggle('open');
  const titles={dashboard:['OVERVIEW','ダッシュボード'],sales:['REVENUE','売上管理'],inventory:['STOCK CONTROL','在庫管理'],attendance:['TIME & ATTENDANCE','勤怠管理'],payroll:['PAYROLL','給与管理'],staff:['TEAM','従業員管理'],news:['INFORMATION','お知らせ']};
  function go(page){$$('.page').forEach(p=>p.classList.toggle('active',p.id===page));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#pageKicker').textContent=titles[page][0];$('#pageTitle').textContent=titles[page][1];$('.sidebar').classList.remove('open');}
  $$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-jump]').forEach(b=>b.onclick=()=>go(b.dataset.jump));
  function renderAll(){renderDashboard();renderSales();renderInventory();renderAttendance();renderStaff();renderNews();renderPayroll();drawChart()}
  function renderDashboard(){const sales=store.get('sales',[]),inv=store.get('inventory',[]),att=store.get('attendance',[]);const todays=sales.filter(x=>x.date.startsWith(today()));const total=todays.reduce((a,x)=>a+x.total,0),profit=todays.reduce((a,x)=>a+(x.total-x.cost),0);$('#metricSales').textContent=money(total);$('#metricProfit').textContent=money(profit);$('#metricStaff').textContent=(attendanceActive?1:0)+'人';$('#metricLowStock').textContent=inv.filter(x=>x.stock<=x.min).length+'件';$('#recentSales').innerHTML=todays.slice(0,4).map(x=>`<div class="list-row"><div class="list-icon">¥</div><div><strong>${esc(x.product)}</strong><span>${esc(x.staff)}・${x.date.slice(11)}</span></div><b>${money(x.total)}</b></div>`).join('')||'<p>本日の売上はまだありません。</p>';$('#recentNews').innerHTML=store.get('news',[]).slice(0,3).map(x=>`<div class="list-row"><div class="list-icon">✦</div><div><strong>${esc(x.title)}</strong><span>${esc(x.body)}</span></div><b>${x.date.slice(5)}</b></div>`).join('')}
  function renderSales(){const q=($('#saleSearch').value||'').toLowerCase(),filter=$('#saleFilter').value;let rows=store.get('sales',[]).filter(x=>(x.product+x.staff).toLowerCase().includes(q));if(filter==='today')rows=rows.filter(x=>x.date.startsWith(today()));$('#salesTable').innerHTML=rows.map(x=>`<tr><td>${x.date}</td><td><strong>${esc(x.product)}</strong></td><td>${esc(x.staff)}</td><td>${x.qty}</td><td>${money(x.total)}</td><td>${money(x.total-x.cost)}</td><td><button class="delete-button" data-delete-sale="${x.id}">削除</button></td></tr>`).join('');$$('[data-delete-sale]').forEach(b=>b.onclick=()=>{store.set('sales',store.get('sales',[]).filter(x=>x.id!=b.dataset.deleteSale));renderAll();toast('削除しました')})}
  $('#saleSearch').oninput=renderSales;$('#saleFilter').onchange=renderSales;
  function renderInventory(){const rows=store.get('inventory',[]);$('#inventoryGrid').innerHTML=rows.map(x=>{const low=x.stock<=x.min,p=Math.min(100,Math.round(x.stock/Math.max(x.min,1)*50));return `<article class="stock-card"><div class="stock-head"><h3>${esc(x.name)}</h3><span class="pill ${low?'low':''}">${low?'不足':'正常'}</span></div><div class="stock-number">${x.stock}<small>${esc(x.unit)}</small></div><div class="stock-meta">最低在庫 ${x.min}${esc(x.unit)}</div><div class="progress"><i style="width:${p}%"></i></div></article>`}).join('')}
  function renderAttendance(){const rows=store.get('attendance',[]);$('#attendanceStatus').textContent=attendanceActive?'現在、出勤中です':'現在は退勤中です';$('#attendanceButton').textContent=attendanceActive?'退勤する':'出勤する';$('#attendanceButton').classList.toggle('active',attendanceActive);$('#attendanceTable').innerHTML=rows.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${x.start}</td><td>${x.end||'勤務中'}</td><td>${x.hours||'-'}</td><td><span class="pill ${x.end?'':'low'}">${x.end?'完了':'勤務中'}</span></td></tr>`).join('')||'<tr><td colspan="5">勤務履歴はまだありません。</td></tr>'}
  $('#attendanceButton').onclick=()=>{let rows=store.get('attendance',[]);if(!attendanceActive){rows.push({id:Date.now(),date:today(),start:nowTime(),end:'',hours:''});attendanceActive=true;toast('出勤しました')}else{let r=[...rows].reverse().find(x=>!x.end);if(r){r.end=nowTime();const [sh,sm]=r.start.split(':').map(Number),[eh,em]=r.end.split(':').map(Number);r.hours=((eh*60+em-sh*60-sm)/60).toFixed(1)+'時間'}attendanceActive=false;toast('退勤しました')}store.set('attendance',rows);store.set('attendanceActive',attendanceActive);renderAll()};
  function renderStaff(){$('#staffGrid').innerHTML=store.get('staff',[]).map(x=>`<article class="staff-card"><div class="staff-head"><div class="staff-avatar">${esc(x.name.slice(0,1))}</div><span class="pill">${esc(x.status)}</span></div><h3>${esc(x.name)}</h3><p>${esc(x.role)}</p><div class="staff-stats"><div><span>30分給</span><strong>${money(x.rate)}</strong></div><div><span>権限</span><strong>${x.role==='Owner'?'管理者':'スタッフ'}</strong></div></div></article>`).join('')}
  function renderNews(){$('#newsGrid').innerHTML=store.get('news',[]).map(x=>`<article class="news-card"><time>${x.date}</time><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join('')}
  function renderPayroll(){$('#payrollGrid').innerHTML=store.get('payroll',[]).map(x=>`<article class="pay-card"><span class="pill">${esc(x.period)}</span><h3>${esc(x.name)}</h3><div class="pay-total">${money(x.base+x.bonus+x.farm)}</div><div class="pay-lines">基本給 ${money(x.base)}<br>ボーナス ${money(x.bonus)}<br>Farm手当 ${money(x.farm)}</div></article>`).join('')}
  function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  const modal=$('#modal'); function openModal(title,kicker,fields,onSave){$('#modalTitle').textContent=title;$('#modalKicker').textContent=kicker;$('#modalFields').innerHTML=fields.map(f=>`<div class="modal-field"><label>${f.label}</label><input name="${f.name}" type="${f.type||'text'}" ${f.value!==undefined?`value="${esc(f.value)}"`:''} ${f.required===false?'':'required'}></div>`).join('');modal.showModal();$('#modalForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));onSave(data);modal.close();renderAll()}}
  $('#addSaleButton').onclick=()=>openModal('売上登録','NEW SALE',[{name:'product',label:'商品名'},{name:'staff',label:'担当者'},{name:'qty',label:'数量',type:'number',value:1},{name:'total',label:'売上金額',type:'number'},{name:'cost',label:'原価',type:'number'}],d=>{const a=store.get('sales',[]);a.unshift({id:Date.now(),date:today()+' '+nowTime(),product:d.product,staff:d.staff,qty:+d.qty,total:+d.total,cost:+d.cost});store.set('sales',a);toast('売上を登録しました')});
  $('#addStockButton').onclick=()=>openModal('商品追加','NEW STOCK',[{name:'name',label:'商品名'},{name:'stock',label:'現在庫',type:'number'},{name:'min',label:'最低在庫',type:'number'},{name:'unit',label:'単位',value:'個'}],d=>{const a=store.get('inventory',[]);a.push({id:Date.now(),name:d.name,stock:+d.stock,min:+d.min,unit:d.unit});store.set('inventory',a);toast('商品を追加しました')});
  $('#addStaffButton').onclick=()=>openModal('従業員追加','NEW MEMBER',[{name:'name',label:'名前'},{name:'role',label:'役職'},{name:'rate',label:'30分給',type:'number'}],d=>{const a=store.get('staff',[]);a.push({id:Date.now(),name:d.name,role:d.role,rate:+d.rate,status:'在籍'});store.set('staff',a);toast('従業員を追加しました')});
  $('#addNewsButton').onclick=()=>openModal('お知らせ作成','NEW POST',[{name:'title',label:'タイトル'},{name:'body',label:'本文'}],d=>{const a=store.get('news',[]);a.unshift({id:Date.now(),date:today(),title:d.title,body:d.body});store.set('news',a);toast('お知らせを公開しました')});
  $('#addPayrollButton').onclick=()=>openModal('給与明細','NEW PAYROLL',[{name:'name',label:'従業員名'},{name:'base',label:'基本給',type:'number'},{name:'bonus',label:'ボーナス',type:'number'},{name:'farm',label:'Farm手当',type:'number',value:500000}],d=>{const a=store.get('payroll',[]);a.unshift({id:Date.now(),name:d.name,period:'今週',base:+d.base,bonus:+d.bonus,farm:+d.farm});store.set('payroll',a);toast('給与明細を作成しました')});
  function drawChart(){const c=$('#salesChart'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth,h=190;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const vals=[42,58,51,74,66,92,81],max=100,pad=24;ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue('--line');ctx.lineWidth=1;for(let i=0;i<4;i++){let y=pad+(h-pad*2)*i/3;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke()}const grad=ctx.createLinearGradient(0,20,0,h);grad.addColorStop(0,'rgba(118,88,68,.28)');grad.addColorStop(1,'rgba(118,88,68,0)');ctx.beginPath();vals.forEach((v,i)=>{const x=pad+(w-pad*2)*i/(vals.length-1),y=h-pad-(h-pad*2)*v/max;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.lineTo(w-pad,h-pad);ctx.lineTo(pad,h-pad);ctx.closePath();ctx.fillStyle=grad;ctx.fill();ctx.beginPath();vals.forEach((v,i)=>{const x=pad+(w-pad*2)*i/(vals.length-1),y=h-pad-(h-pad*2)*v/max;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#765844';ctx.lineWidth=3;ctx.lineJoin='round';ctx.stroke()}
  window.addEventListener('resize',drawChart);setInterval(()=>{const d=new Date();$('#clockDate').textContent=d.toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'});$('#clockTime').textContent=d.toLocaleTimeString('ja-JP')},1000);
  if(sb){sb.auth.getSession().then(({data})=>{if(data.session){currentUser={name:data.session.user.user_metadata?.name||data.session.user.email.split('@')[0],email:data.session.user.email};role=data.session.user.email===cfg.ADMIN_EMAIL?'admin':'employee';openApp()}})}
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(console.warn);
})();
